name: 'vswhere'
description: 'Helps to find files from Visual Studio installations.'
author: 'Lectem'
branding:
  color: purple
  icon: terminal
inputs:
  file:
    required: true
    description: | 
      'The action will add ot the path the directory containing the matching file under the installation path.'
      'Will look recursively through folders.'
      '`?``  Matches any one character except `\`'
      '`*``  Matches zero or more characters except `\`'
      '`**` Searches the current directory and subdirectories for the remaining search pattern'
  vswhere-path:
    required: false
    description: 'Folder location of where vswhere.exe is located if a self-hosted agent'
  vs-version:
    description: 'Version of Visual Studio to search; defaults to latest if not specified'
    required: false
  vs-prerelease:
    description: 'Enable searching for pre-release versions of Visual Studio/MSBuild'
    required: false
  requires:
    description: 'Specifies the required Visual Studio components. It expects a string containing the list of components seperated by spaces. See https://aka.ms/vs/workloads for a list of workload and component IDs.'
    required: false
  requires-any:
    description: 'Find instances with any one or more workload or components IDs passed to -requires.'
    required: false
outputs:
  filePath:
    description: 'The resulting location of the file for your inputs'

runs:
  using: 'node16'
  main: 'dist/index.js'
